### ISSUE TITLE
auto return type

### ISSUE THREAD

**Issue by polyvertex** [Morwenn/cpp-sort#100]
Hi, more a question than an issue. I stumbled upon you repo while doing some research about, well, sorting algorithms obviously. A bit of "reviewing" lead me to encounter a lot declarations in your code similar to:
```c++
auto sort(Iterable&& iterable) -> void
```

I failed to find any technical reason that would lead me to use the `auto` keyword here and not to specify the return type directly in this kind of cases (and on a more subjective note it hurts a bit!), but I thought I may have missed something. So is it purely out of aesthetic/cosmetic reasons?

**Comment by Morwenn** [comment]
It's mostly a matter of taste. There are two main reasons for this choice:
* I often need to `decltype` the parameters in the return type, so using the trailing return type syntax everywhere is more consistent.
* I like it more (also, I always find it more logical to specify the return type after the arguments: a function takes parameters, *then* potentially returns something).

I am fully aware that it hurts most people, often because old habits die hard :p

**Comment by polyvertex** [comment]
Ah! I wouldn't invoke *old habits* here as `auto sort() -> void`, pulled out of its context (which is unfair admittedly), is noisy since it uses more language tooling than necessary. Preventing your code to be *pure*. Readability on the other hand, balances your choice and made it the most guessable reason (anthropology from code poetry is fun). Anyway this second reason of yours was the one I was missing and the reason why I asked. Thanks!

**Comment by Morwenn** [comment]
Just replace `auto` by `def` or `fn` or `func`, and then it will look like the syntax of many modern languages: just look at Rust, Swift or Python 3 (with type annotations). The programming world seems to be moving to a « trailing return type on the right ». The only possible confusion is that C++ used `auto` for backward compatibility, which is a bit meh because it's already used in many places, but I don't really find it noisy (at least less noisy than `superlongreturntype yaymyfuncname(datsuperparameter, datothersuperparameter)` put on the same line (I've often seen that, not everybody likes to put the return type on another line). The `->` is IMHO easier to visually identify than a mere space to separate the function name from its return type.

I don't understand that *pure* thing.

**Comment by polyvertex** [comment]
The construction of `void sort() -> auto` is noisy in the sense that « it uses more language tooling than necessary » (hence the `!pure` statement). No matter your/my visual preferences/habits here. In C++, `void sort() -> auto` is more noisy than `void sort()` because the former is unnecessary. That is obviously the result of a deliberate and strong stylistic choice from the author (you). The purpose of my initial question was to ensure I understand why.

I do not share your reading on *modern languages* though. Venerable (as in « definitely not modern ») Lisp for example, allows similar semantics. I wouldn't make that a trend, if any.

**Comment by Morwenn** [comment]
I guess that I simply don't understand that « more language tooling » part. To me `void sort()` and `auto sort() -> void` use exactly as many tools, albeit with a different syntax.

I didn't mean to say that older languages didn't use trailing returns types, but that most somewhat successful modern languages tend to use them (Go, Swift, Rust, Scala, Kotlin, Nim, TypeScript...). Except when they need to maintain backwards compatibility with languages with the return type on the left of course (like Groovy).

**Comment by polyvertex** [comment]
> I guess that I simply don't understand that « more language tooling » part. To me `void sort()` and `auto sort() -> void` use exactly as many tools, albeit with a different syntax.

Isn't it the subject here? Syntax? Style? While there's no discussion about how both forms result after compilation (thanks for not shaming me about the typo in my previous comment BTW), paths differ as to the parsing and interpretation steps (or semantic analysis if you opt for the pedantic way). For instance, the `-> decltype(auto)` case you mentioned earlier as a being part of the primary reason of your choice, has been introduced in C++ so the return type deduction can be delayed, allowing/easing SFINAE in turn. Call that a langage feature, a syntactic tool, whatever, bottom line is, you tell the compiler a different story so that makes your « use exactly as many tools » statement incorrect in this context since you do not specify the return type per-se. You defer its deduction (or its definition in this specific case, since you directly use `void`). Out of the two forms (`auto sort() -> void` and `void sort()`), one is de facto unnecessarily noisier than the other.

Going further, this noise you add may even become error-prone for the reader in some real-world cases. For example:
```c++
// not-so-obvious return type difference for the reader
auto f(int x) -> decltype(x) { ... }
auto f(int x) -> decltype((x)) { ... }

// as opposed to
int f(int x) { ... }
int& f(int x) { ... }
```

---

> I didn't mean to say that older languages didn't use trailing returns types ...

What I meant to say in return is that I don't share your reading because I don't think there is a particular trend on that topic and also because I try to avoid making out figures out of the blue as I don't have sufficient knowledge/experience of/with all the languages (no pun intended). Being they recent or not.

Would any trend exist, I would not consider it so relevant that I invoke it to "justify" my code style. Or, inversely, I wouldn't try to apply this trend to a specific language just because it's like that in other languages neither. My point being that trying to identify some syntactic patterns across languages may be misleading and may bias your understanding of the actual meaning of their natural structure (most obvious real-world example crossing my mind being people writing `C/C++` on their résumé; a non-sense that reveals a significant lack of experience with both languages and that incidentally makes them candidates of poor choice for a job).

I got your point though: consistent in local code, consistent perhaps also in global trend as well (c'est un peu capilo-tracté mais ça passe).

Well, this could go all year I suppose. I appreciate you do have a reasoning behind your code, which in the end is probably the most important thing as a developer I believe, and which also happens to be a strong pro for a code library. So thanks again for taking the time to clarify the reasoning behind your choice.

**Comment by vendethiel** [comment]
> Going further, this noise you add may even become error-prone for the reader in some real-world cases. For example:

That's a strawman.
You can perfectly write 

```c++
auto f(int x)
 -> int&
```

The idea here is to keep it consistent and on its own lines. `decltype()` is yet another feature and needn't be mentioned here.

**Comment by polyvertex** [comment]
@vendethiel obviously you didn't get my point.

**Comment by Morwenn** [comment]
There isn't any deferred deduction with `auto foobar() -> void` either; `decltype()` is totally orthogonal to the trailing return type syntax. Either I don't get your point, or I don't buy it :/

**Comment by polyvertex** [comment]
Where did I state that `auto f() -> void` form implies deferred deduction? Lecturing on `decltype()` properties was unnecessary (in addition of being slightly pedantic). We're at syntax level, subject being readability and my point was that your `use exactly as many tools` statement is incorrect here.

**Comment by Morwenn** [comment]
> Going further, this noise you add may even become error-prone for the reader in some real-world cases

**Comment by polyvertex** [comment]
My "wall of text" as you call it was a sincere and non-offensive detailing of my approach, while trying to explain what you claimed not to understand. Obviously I was in the wrong place for a nice debate. Sorry you had to expose your childish attitude twice to make me understand.

**Comment by Morwenn** [comment]
Sorry if I sounded offensive, that wasn't the point. See you another day then :3

<3

**Comment by vendethiel** [comment]
There's no debate when you're wrong.

**Comment by milleniumbug** [comment]
If you have so much time bikeshedding over syntactic issues, just wait until you reach issues which affect semantics. 

I think this is the "tabs vs spaces" of this decade.

In the time you'll be spending bikeshedding, I'll have a working product.

**Comment by polyvertex** [comment]
@milleniumbug that's a nice way to say you agree on what I wrote actually. Still my intent was not to prove anything or to impose my point of view but to explain what @Morwenn claimed not to understand in my previous comment. Bike-shedding stopped with my first reply. The following was an effort I now regret as I didn't know I was getting into so much trouble and about to face sarcasm and punchlines. My mistake.

**Comment by Optiligence** [comment]
Just to randomly chime in: I think @polyvertex hiccup is that the use of `auto` (and trailing return types) is a(n unnecessary) use of a(n additional) language feature whereas the other viewpoint is, that it’s just an artifact when uniformly using right-hand side notation of return types for consistency within the project and with other languages.

**Comment by Morwenn** [comment]
Hum, that may be it. While my point of view if that `void foobar()` and `auto foobar() -> void` is exactly the same language feature albeit with a different, and that none of them is « an additional language feature ». Hence in the end (unless there's more than that, which I wasn't sure), it's more of an « I don't buy it » than and « I don't get it ».

Anyway, thanks for trying to intervene calmly in an issue that was already pretty heated for no good reason :)

**Comment by polyvertex** [comment]
An example reduced to its simplest form like `void f()` vs. `auto f() -> void` does not help much to illustrate how this can be of an issue. Hence the use of `decltype` in an other example. The `decltype((x))` notation is confusing for some, plus the visual difference against `decltype(x)` is not so obvious to peek; which makes it a better example in this context *if and only if* it can be reduced directly by the coder to something like `int& f(int x)` and `int f(int x)` respectively (see comment above for the full version). Barking watchdogs aside, I think it's easy for any team-player to grasp that both syntaxes differ and that one of them, in addition of being unnecessary technically-wise, may lead to confusion despite the heavy (good) weight of style consistency on the other side of the balance.

In the light of this, a rule of thumb might be to avoid using constructions that would potentially confuse the reader, if possible. One may subscribe to it or not, it's a matter of choice as much as coding style can be. But this issue does exist and the bigger the team working on the same piece of code, the higher the risk of confusion and misinterpretation. Readability and aesthetic are not the only reasons why coding guidelines are made for. And yes, consistency definitely becomes a factor of choice here.

Now, there was just a question, then an answer and may it matters, I find @Morwenn's code clear anyway so there was no argument against the code in this repo. And thanks @Optiligence for being reasonable.

**Comment by Morwenn** [comment]
So in the end, it's more against unnecessary `decltype` (and more generally against somewhat tricky type deduction when it's not needed) than against unnecessary trailing return type syntax, right? In which case I do agree.

**Comment by polyvertex** [comment]
It can be worded like that yes, although it's not specifically about type deduction or return type syntax.
