### ISSUE TITLE
Smaller sorting networks for 20, 23 and 24 inputs

### ISSUE THREAD

**Issue by bertdobbelaere** [Morwenn/cpp-sort#119]
Hi Morwenn,

I understood you were interested in further reduced sorting network sizes. I did some personal research on the subject and can contribute the following networks.
All three are AFAIK networks with the smallest number of pairs at this time for their number of inputs.
Please verify correctness before integrating them.

Kind regards,
Bert Dobbelaere.

Network for N=20, size=91, depth=12:
[ [(0, 3), (1, 7), (2, 5), (4, 8), (6, 9), (10, 13), (11, 15), (12, 18), (14, 17), (16, 19)] ,
[(0, 14), (1, 11), (2, 16), (3, 17), (4, 12), (5, 19), (6, 10), (7, 15), (8, 18), (9, 13)] ,
[(0, 4), (1, 2), (3, 8), (5, 7), (11, 16), (12, 14), (15, 19), (17, 18)] ,
[(1, 6), (2, 12), (3, 5), (4, 11), (7, 17), (8, 15), (13, 18), (14, 16)] ,
[(0, 1), (2, 6), (7, 10), (9, 12), (13, 17), (18, 19)] ,
[(1, 6), (5, 9), (7, 11), (8, 12), (10, 14), (13, 18)] ,
[(3, 5), (4, 7), (8, 10), (9, 11), (12, 15), (14, 16)] ,
[(1, 3), (2, 4), (5, 7), (6, 10), (9, 13), (12, 14), (15, 17), (16, 18)] ,
[(1, 2), (3, 4), (6, 7), (8, 9), (10, 11), (12, 13), (15, 16), (17, 18)] ,
[(2, 3), (4, 6), (5, 8), (7, 9), (10, 12), (11, 14), (13, 15), (16, 17)] ,
[(4, 5), (6, 8), (7, 10), (9, 12), (11, 13), (14, 15)] ,
[(3, 4), (5, 6), (7, 8), (9, 10), (11, 12), (13, 14), (15, 16)] ]

Network for N=23, size=116, depth=14 :
[ [(0, 12), (1, 7), (2, 8), (3, 17), (4, 9), (5, 13), (6, 20), (10, 18), (14, 19), (15, 21), (16, 22)] ,
[(0, 5), (1, 16), (2, 15), (3, 4), (6, 14), (7, 22), (8, 21), (9, 17), (10, 11), (12, 13), (19, 20)] ,
[(0, 3), (4, 5), (6, 10), (7, 15), (8, 16), (9, 12), (11, 14), (13, 17), (18, 19)] ,
[(3, 11), (4, 10), (5, 14), (9, 18), (12, 20), (13, 19)] ,
[(2, 3), (8, 11), (12, 15), (20, 21)] ,
[(1, 3), (2, 6), (7, 12), (11, 16), (17, 21), (20, 22)] ,
[(0, 1), (3, 8), (7, 11), (12, 16), (15, 20), (17, 22)] ,
[(0, 2), (1, 6), (3, 9), (4, 7), (5, 15), (8, 18), (10, 12), (11, 13), (14, 20), (16, 19)] ,
[(1, 3), (2, 4), (5, 10), (6, 9), (8, 11), (12, 15), (13, 18), (14, 17), (19, 21), (20, 22)] ,
[(1, 2), (3, 4), (5, 6), (7, 11), (9, 10), (12, 16), (13, 14), (17, 18), (19, 20), (21, 22)] ,
[(2, 3), (6, 8), (7, 9), (10, 11), (12, 13), (14, 16), (15, 17), (20, 21)] ,
[(4, 7), (5, 6), (8, 9), (10, 12), (11, 13), (14, 15), (16, 19), (17, 18)] ,
[(4, 5), (6, 7), (8, 10), (9, 12), (11, 14), (13, 15), (16, 17), (18, 19)] ,
[(3, 4), (5, 6), (7, 8), (9, 10), (11, 12), (13, 14), (15, 16), (17, 18), (19, 20)] ]

Network for N=24, size=121, depth=14:
[ [(0, 12), (1, 7), (2, 8), (3, 17), (4, 9), (5, 13), (6, 20), (10, 18), (11, 23), (14, 19), (15, 21), (16, 22)] ,
[(0, 5), (1, 16), (2, 15), (3, 4), (6, 14), (7, 22), (8, 21), (9, 17), (10, 11), (12, 13), (18, 23), (19, 20)] ,
[(0, 3), (4, 5), (6, 10), (7, 15), (8, 16), (9, 12), (11, 14), (13, 17), (18, 19), (20, 23)] ,
[(3, 11), (4, 10), (5, 14), (9, 18), (12, 20), (13, 19)] ,
[(2, 3), (8, 11), (12, 15), (20, 21)] ,
[(1, 3), (2, 6), (7, 12), (11, 16), (17, 21), (20, 22)] ,
[(0, 1), (3, 8), (7, 11), (12, 16), (15, 20), (22, 23)] ,
[(0, 2), (1, 6), (3, 9), (4, 7), (5, 15), (8, 18), (10, 12), (11, 13), (14, 20), (16, 19), (17, 22), (21, 23)] ,
[(1, 3), (2, 4), (5, 10), (6, 9), (8, 11), (12, 15), (13, 18), (14, 17), (19, 21), (20, 22)] ,
[(1, 2), (3, 4), (5, 6), (7, 11), (9, 10), (12, 16), (13, 14), (17, 18), (19, 20), (21, 22)] ,
[(2, 3), (6, 8), (7, 9), (10, 11), (12, 13), (14, 16), (15, 17), (20, 21)] ,
[(4, 7), (5, 6), (8, 9), (10, 12), (11, 13), (14, 15), (16, 19), (17, 18)] ,
[(4, 5), (6, 7), (8, 10), (9, 12), (11, 14), (13, 15), (16, 17), (18, 19)] ,
[(3, 4), (5, 6), (7, 8), (9, 10), (11, 12), (13, 14), (15, 16), (17, 18), (19, 20)] ]

**Comment by Morwenn** [comment]
Wow, thank you very much, I'll try to check them later today, thanks a lot! :)

**Comment by Morwenn** [comment]
I validated the three of them and integrated them to the library, thanks again!

May I know how you found them? Even smart genetic algorithms and the like weren't able to find sorting networks with a size under 92 for 20 inputs. What you've done looks like an impressive feat and beats everything I could find in literature so far.

**Comment by bertdobbelaere** [comment]
That was quick! 
The method I used to obtain these results was an evolutionary approach, in which I started with a random valid sorter and iteratively applied mutations to come to a result of smaller size. For sizes 20 and 24, the network was kept symmetric by construction, the case for 23 was obtained by simply removing an input from the 24 case. 
- Initial conditions are established by starting from an empty network and randomly adding sorting nodes (i.e. CEs) until the sorter is valid. Nodes are duplicated (except if connecting symmetric inputs) so the network remains symmetric

- Following mutations are applied with equal "high" probability, and are accepted as long as the network remains a valid sorter:

    1. Remove a random node (and its mirror image)

    1. Swap two nodes at random positions (and their mirror images)

    1. Replace a node with another random node (update mirror image)

    1. Cross two nodes (and their symmetric counterparts) by combining elements of both to two new nodes (only applied in the '24' case)

- Another, "low" probability mutation is the addition of a node (+its mirror image). No acceptance check here. The idea is to try to escape local minima. 

I tried various implementation variants. For the cases mentioned here, I was able to improve previous results, no such luck for other sizes so far.

**Comment by Morwenn** [comment]
That's pretty interesting: on the one hand the symmetry approach is quite close to algorithms already used to discover new networks, on the other hand the mutations applied feel simpler and more pragmatic than some of the clever approaches used recently in other papers, yet it was able to yield better results.

While I always thought we could discover new networks for 23 and 24 inputs with current technology (the gap in size between 22 and 23 was quite high), I'm rather impressed that you also managed to find one for 20 inputs, moreover one that is only one parallel step away from the most well-known depth for that many inputs.

**Comment by bertdobbelaere** [comment]
There's still low hanging fruit there! 
Especially in the trade-off cases: papers I found focussed either on size or on depth, while a practical implementation usually picks a trade-off between both aspects, depending on HW architecture.
E.g. the case for N=17:
The paper of Valsalam&Miikkulainen focussed on size and produced S=71 D=17
The paper of Ehlers&Mueller focussed on depth and produced S=79 D=10
I broke neither depth nor size records, but was able to produce
(D,S)= {(75,10),(73,11)},(71,12)} combinations so far.

BTW: the depth of the N=24 and N=23 cases has gone down to 13 since yesterday :-)
Below is N=24,S=121,D=13. Case for N=23 obtained by removing pairs containing 23

[ [(0, 2), (1, 8), (3, 18), (4, 17), (5, 20), (6, 19), (7, 9), (10, 11), (12, 13), (14, 16), (15, 22), (21, 23)] ,
[(0, 3), (1, 15), (2, 18), (4, 12), (5, 21), (6, 10), (7, 14), (8, 22), (9, 16), (11, 19), (13, 17), (20, 23)] ,
[(0, 4), (1, 7), (2, 13), (3, 12), (5, 6), (8, 14), (9, 15), (10, 21), (11, 20), (16, 22), (17, 18), (19, 23)] ,
[(0, 5), (2, 11), (3, 6), (4, 10), (8, 9), (12, 21), (13, 19), (14, 15), (17, 20), (18, 23)] ,
[(1, 5), (2, 8), (3, 9), (6, 7), (14, 20), (15, 21), (16, 17), (18, 22)] ,
[(0, 1), (3, 5), (4, 6), (8, 10), (9, 11), (12, 14), (13, 15), (17, 19), (18, 20), (22, 23)] ,
[(1, 3), (2, 4), (5, 13), (7, 11), (8, 9), (10, 18), (12, 16), (14, 15), (19, 21), (20, 22)] ,
[(1, 2), (3, 4), (6, 12), (7, 13), (10, 16), (11, 17), (19, 20), (21, 22)] ,
[(2, 3), (4, 5), (6, 8), (7, 10), (9, 12), (11, 14), (13, 16), (15, 17), (18, 19), (20, 21)] ,
[(4, 6), (5, 8), (7, 9), (10, 12), (11, 13), (14, 16), (15, 18), (17, 19)] ,
[(3, 4), (5, 7), (8, 11), (9, 10), (12, 15), (13, 14), (16, 18), (19, 20)] ,
[(6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)] ,
[(5, 6), (7, 8), (9, 10), (11, 12), (13, 14), (15, 16), (17, 18)] ]

**Comment by Morwenn** [comment]
Oh, I thought that a practical implementation would rather have the smallest depth so that it can run more things in parallel. I admit that I don't know actual real world cases where sorting networks might be used. I only focus on size because I don't actually run the comparisons and swaps in parallel, so my goal is to have networks that produce the smallest sequential instructions (until I go full SIMD for some algorithms, but I probably won't try before a while).

Have you considered writing a paper about your findings or trying to share them more broadly (*e.g.* on arXiv.org if you don't want to target more "official" research platforms)? I mean, what you found does beat the current research results and your approach might be interesting enough to warrant broader visibility (I don't think anyone actually uses my library for anything serious, let alone the sorting network sorting, so that won't give much visibility). Anyway, it's up to you what you want to do with that at the end of the day :)

**Comment by bertdobbelaere** [comment]
FYI: Just created the SorterHunter repo.

**Comment by Morwenn** [comment]
Oh, you managed to improve several bounds even more, that's impressive :o

I'm tracking your repo then in case there are more results to come. Your website about the bet known sorting networks is great too; such a resource was lacking when I started to implement sorting networks here :)

**Comment by Morwenn** [comment]
I've just updated everything again to your latest results, and tested the networks independently (except for 28 inputs, I don't have that kind of time ^^'). Thanks again for everything!
