### ISSUE TITLE
Review for inclusion request in conan-center@bintray

### ISSUE THREAD

**Issue by pvicente** [Morwenn/cpp-sort#124]
Hi Morwenn,

I've been checking this inclusion request and everything **looks ok** with the **conan recipe** for this header only library, **so congratulations**!!! 

I've followed the contribution guidelines and I only have a few comments about the [package information reported in bintray](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html?highlight=guidelines#bintray-package-information)

Please add the following changes in your [bintray package](https://bintray.com/morwenn/cpp-sort/cpp-sort%3Amorwenn):

- Better description for the package:
    - currently: Additional sorting algorithms & related tools 
    - proposed: Additional sorting algorithms for C++14 and C++17
- Set the following fields in Bintray:
    - Image (if available)
    - Website
    - Issue Tracker
    - Product Maturity
- Search tags for Bintray (optional)

As an example you can have a look at [boost package](https://bintray.com/conan-community/conan/boost%3Aconan) which is reporting this information.

**Thank you for your contribution**,
Pedro

**Comment by vendethiel** [comment]
you're missing `](` in your markdown.

**Comment by pvicente** [comment]
what about now?

**Comment by Morwenn** [comment]
Hi, thanks a lot for accepting the request :)

I completed the package information, and only have a remark about the description: I reckon that mentioning C++14 matters, but I think that I can drop the C++17 part: when everything goes well a C++14 library is also supposed to work with C++17 and newer standards. Plus the library contains a bit more than just sorting algorithms. What about the following:

> Sorting algorithms & related tools for C++14

I think it would be enough. Now it would be better if Bintray correctly rendered the ampersamp in the description :p

**Comment by pvicente** [comment]
Yes no problem about that!!! It's your library only put a description that matches with your goals.

After that change everything will be ready to accept the inclusion request. Let me know and I'll click the button.

Thanks,
Pedro

**Comment by Morwenn** [comment]
Consider it done :)

**Comment by pvicente** [comment]
Congratulations your contribution is already in [conan-center](https://bintray.com/conan/conan-center?filterByPkgName=cpp-sort%3Amorwenn).

```
$ conan search *cpp-sort* -r conan-center
Existing package recipes:

cpp-sort/1.0.0@morwenn/stable
```
All the best,
Pedro

**Comment by Morwenn** [comment]
Thanks for everything!

I'm closing the issue now that this is done.
