### ISSUE TITLE
Modern CMake for fun & profit

### ISSUE THREAD

**Issue by Morwenn** [Morwenn/cpp-sort#135]
The current CMake is "pragmatic" which means that it roughly gets the job done somehow and that's pretty much it. It should be time to read some tutorials and actually get some decent modern CMake in this library, especially now that Catch2 provides a modern CMake interface.

Myabe throw in some ideas from here as well: https://github.com/vector-of-bool/vector-of-bool.github.io/blob/master/_drafts/project-layout.md

**Comment by stefanos82** [comment]
What's your opinion for Meson?

Personally I find it much more convenient and a lot easier to use than CMake.

For some reason, I cannot fathom CMake...don't ask why :confused:

**Comment by Morwenn** [comment]
I don't have any opinion because I never tried Meson.

I simply picked CMake because it's apparently the most used, which makes it easier to find examples and help. Plus it's also the one used by the testing framework used by cpp-sort, Catch2, which also provides a few tools to make tests discovery easier.

Save for a few problems linked to valgrind command line options, the `modern-cmake` branch is almost finished anyway :p

**Comment by Morwenn** [comment]
Not really, I first looked at a few articles, mostly the ones below:
* https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/
* https://unclejimbo.github.io/2018/06/08/Modern-CMake-for-Library-Developers/
* https://github.com/vector-of-bool/vector-of-bool.github.io/blob/master/_drafts/project-layout.md

I then compared this new-found knowledge to other header-only projects, tried to get a first semi-working version for this library then solved the specific problems I had one one, by looking at StackOverflow questions & answers, or old forum posts or mailing lists, or by checking how other projects solved similar problems. CMake has a complete reference, but it is true that it lacks examples of how to use things properly. More often than not I end up looking for solutions on the internet and/or trying things that seem to make sense.

**Comment by Morwenn** [comment]
Closed by #137, which roughly does the following:
* Properly create, use and export CMake target
* Install CMake files
* Download Catch2 during the configuration step, not the build step
* Automatically discover Catch2 tests instead of having a single test for the whole test suite
* Use Valgrind through CTest memcheck step
