### ISSUE TITLE
Memory allocation strategies for buffered sorts

### ISSUE THREAD

**Issue by Morwenn** [Morwenn/cpp-sort#37]
Some sorting algorithms such as block sort and grail sort optionally use a buffer, either fixed or dynamic (in which case it often depends on the size of the input) to speed up the sorting process and exhibit somewhat significant performance changes depending on how the buffer is allocated. As things are right now, block sort uses a fixed-size 512 elements buffer and I plan to implement the version of grail sort that uses no buffer at all (SqrtSort is a variation of grail sort using a buffer whose size corresponds to the square root of the size of the input). I wish there was a simple way for users to use different buffering strategies for the same algorithms depending on their needs, but really don't see how: adding new parameters to the functions would be a mess (named parameters would be great though) and adding a template parameter does not feel like the greatest idea in the world either.

Another solution would be to give *sorters* a template parameter corresponding to the buffering strategy, but it wouldn't be as nice syntax-wise because of the mandatory diamond `<>` even for the default buffering strategy. I'm a bit short on ideas for this one. New ideas are welcome.

Examples of usage:

    using sorter1 = block_sorter<fixed_buffer<512>>;
    using sorter2 = grail_sorter<dynamic_buffer<sqrt>>;

Apparenty, the code above needs something akin to partial application of template parameters or template template alias in order to work. There *is* a workaround though: even though it makes writing buffer providers harder, it makes writing and using buffered sorters easier:

    template<std::size_t N>
    struct fixed_buffer
    {
        template<typename T>
        struct implementation
        {
            implementation(std::size_t size) { /* discard size */ }

            auto begin() const { return std::begin(data); }
            auto end() const { return std::end(data); }

            T data[N]; // actual buffering memory
        };
    };

The buffered sorting algorithms would then use `Buffer::template implementation<T>` to get an instance of the actual buffer provider. That said,  `implementation` is an ugly name, and we can probably do better. The function object types `log` and `sqrt` could live in a `<cpp-sort/utility/functional.h>` header where we could also move `utility::identity` for consistency. The templates `fixed_buffer` and `dynamic_buffer` could live in the header `<cpp-sort/utility/memory.h>`.

---

Things are becoming clearer. We can probably go on with the following roadmap:
- [x] Implement `fixed_buffer`, taking a size.
- [x] Implement `dynamic_buffer`, taking a size policy.
- [x] Implement basic function objects such as `log` and `sqrt`.
- [x] Update `block_sorter` and give it a default `fixed_buffer<512>` template parameter.
- [x] Add unit tests.
- [ ] Update documentation (`block_sorter`, library concepts and how to write sorters).

Open questions: what about allocators? Do we want them as an additional template parameter for `dynamic_buffer`? Is there a way to wrap `std::get_temporary_buffer` to allocate some memory on the fly? Should it take a function object parameter like `dynamic_buffer`?

**Comment by vendethiel** [comment]
(typo: memery)

**Comment by Morwenn** [comment]
@vendethiel To be honest I fixed the title *then* saw your comment :p
