### ISSUE TITLE
Add undefined behaviour sanitizer

### ISSUE THREAD

**Issue by Morwenn** [Morwenn/cpp-sort#49]
While Valgrind is pretty cool, there can't be too many tools checking for potential undefined behaviour. We could add the undefined behaviour sanitizer to the Debug mode:
- [x] Don't use it with MinGW since it is not supported.
- [x] Use it with GCC on Linux.
- [x] Use it with Clang on Linux.

Unfortunately, it doesnt "just" work with Clang. hen I try to add `-fsanitize=undefined`, I get [the following error][1]:

    Linking CXX executable cpp-sort-testsuite
    /usr/bin/ld: cannot find /usr/lib/llvm-3.8/bin/../lib/clang/3.8.0/lib/linux/libclang_rt.ubsan_standalone-x86_64.a: No such file or directory
    /usr/bin/ld: cannot find /usr/lib/llvm-3.8/bin/../lib/clang/3.8.0/lib/linux/libclang_rt.ubsan_standalone_cxx-x86_64.a: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [testsuite/cpp-sort-testsuite] Error 1
    make[1]: *** [testsuite/CMakeFiles/cpp-sort-testsuite.dir/all] Error 2
    make: *** [all] Error 2

It feels like some files are missing from the Linux VM on Travis, but I can't confirm for sure... Any help to solve this issue is welcome :)

  [1]: https://travis-ci.org/Morwenn/cpp-sort/jobs/104667231

**Comment by vendethiel** [comment]
http://stackoverflow.com/questions/1867745/cmake-use-a-custom-linker ?(2nd answer esp.)

**Comment by Morwenn** [comment]
Yeah, I read that one, but actually finding where the correct linker is is a difficult task by itself: apparently, there was something called `llvm-ld` until Clang 3.2, then they dropped it and it appears that something called `lld` exists nowadays. Not sure how to make CMake find it without giving a raw path.

The Clang page about ub-chan isn't really helpful either as it doesn't tell *how* we can link things:

> Make sure to use `clang++` (not `ld`) as a linker, so that your executable is linked with proper UBSan runtime libraries.

**Comment by nabijaczleweli** [comment]
Try cooking the path

**Comment by Morwenn** [comment]
Haha, I've not the slightest idea what that's supposed to mean :D

**Comment by nabijaczleweli** [comment]
> Not sure how to make CMake find it without giving a raw path.

Try cooking it.

**Comment by Morwenn** [comment]
I...

**Comment by Morwenn** [comment]
Apparently thee problem [comes from LLVM][1], so there isn't much we can do about it right now. It should be fixed in a near future though. Classing the issue as future until it works out-of-the-box with Travis.

  [1]: https://llvm.org/bugs/show_bug.cgi?id=22757
