### ISSUE TITLE
Test clang++ with both libc++ and libstdc++

### ISSUE THREAD

**Issue by Morwenn** [Morwenn/cpp-sort#65]
Currently the Travis process only checks that the tests run with clang++ in Debug/Release mode with the default standard library (apparently libstdc++). We should update the relevant CMakeLists.txt and the .travis.yml to check that the tests pass with clang++ with both libc++ and libstdc++.

After the clang++-3.8 whitelist thingy is fixed that is... _[Update: solved]_

**Comment by nabijaczleweli** [comment]
Nota bene: "`clang++-3.8` whitelist thingy" is https://github.com/travis-ci/apt-source-whitelist/pull/255

**Comment by Morwenn** [comment]
Xcode uses clang with libc++, so the libc++ are now covered by the OSX builds in the CI.
