### ISSUE TITLE
Linear vs. binary insertion sort

### ISSUE THREAD

**Issue by Morwenn** [Morwenn/cpp-sort#78]
Let's face it: in its current form, `insertion_sorter` is a clusterfuck of bad design. The forward iterators version implements a binary insertion sort while the bidirectional (and thus random-access iterator) version(s) implement a linear insertion sort.

~~Both are useful: the linear one is used as a fallback when there are few elements to sort, and the binary one is useful when there are only a few misplaced elements. Different use cases. The obvious solution would be to have `linear_insertion_sorter` and `binary_insertion_sorter`, but I'd like to have one of them keep the name `insertion_sorter` for brevity (it would probably be the binary version).~~

~~Having an implicit and an explicit name is probably a bad idea too.~~

wat am the do

---

After having given it some thoughts again, it's pretty obvious that binary insertion sort is actually useless. Not sure whether it didn't occured to me before. The solution is obvious: kill binary insertion sort and totally remove the insertion sort support for forward iterators; it's not worth it.

**Comment by hostilefork** [comment]
Kind of fun this issue contains a redaction.

I was telling a non-binary friend about you, you came up in conversation.  So I remembered the time I tried to kind of coax you to come work on things with me, as I have come into a bit of capital.

And you turned me down :-( hey, it's a big world, I get it.  Players gotta play, but I do think some of my ideas are pretty good.

However you mentioned you had dreamed about me.  And so I went to look up the comment.  (I delete all the gmail and hotmail boxes and purge them, I'm a 0K computer, after all.)  Couldn't find the remark:

<img width="785" height="455" alt="Image" src="https://github.com/user-attachments/assets/3a4f1b1b-b041-462e-9c89-29cb563eb38c" />

My friend who wanted to meet you's name is Cypress.  Rock star.  Collects... like... rocks.  US Louisville Citizen with passport.  Bought this lot from someone moving to Lexington.

<img width="2048" height="956" alt="Image" src="https://github.com/user-attachments/assets/8aafcca8-6a90-4197-b6dc-5e04dbbdd17d" />

Anyway my offer still stands, if you feel like working on something and need currency.  AI are great, but not the same.

**Comment by hostilefork** [comment]
Also, asking for queries on this ticket don't work; like "last updated", anyway.  the original dream report was you being surprised at what a large territory I controlled.  So it goes.

I've actually spent time engaging some of these AI.  At times I'm impressed.  This may not be the algorithm, but I think it's good:

https://suno.com/song/1e47b493-842d-4015-9e1f-3e63aa0d411e?sh=hMxkIcE4JTyUXnh1
